message:
  supportedMessageTypes:
    - identify
    - track
  identify:
    transformation:
      mapperPath: ./mapping/identify.yaml
      postMapper:
        name: "identifyPostMapper"
      response:
        method: POST
        format: JSON
        endpoint: "https://heapanalytics.com/api/add_user_properties"
        userId: "{{ message.anonymousId }}"
        headers:
          Accept: "application/json"
          Content-Type: "application/json"

  track:
    transformation:
      mapperPath: ./mapping/track.yaml
      postMapper:
        name: "trackPostMapper"
      response:
        method: POST
        format: JSON
        endpoint: "https://heapanalytics.com/api/track"
        userId: "{{ message.anonymousId }}"
        headers:
          Accept: "application/json"
          Content-Type: "application/json"
        