- destKey: app_tracking_transparency
  sourceKeys: context.device.attTrackingStatus
- destKey: usertime
  sourceKeys:
  - originalTimestamp
  - timestamp
- destKey: app_version
  sourceKeys: context.app.build
- destKey: device_ua
  sourceKeys: context.userAgent
  metadata:
    defaultValue: ''
- destKey: origination_ip
  sourceKeys:
  - context.ip
  - request_ip
- destKey: app_name
  sourceKeys: context.app.name
- destKey: app_short_string
  sourceKeys: context.app.version
- destKey: locale
  sourceKeys: context.locale
- destKey: os_version
  sourceKeys: context.os.version
- destKey: screen_dpi
  sourceKeys: context.screen.density

