message:
  screen:
    transformation:
      mapperPath: ./mapping/default.yaml
      postMapper:
        name: "screenPostMapper"
      response:
        method: POST
        format: JSON
        endpoint: "https://control.kochava.com/track/json"
        userId: "{{ message.anonymousId }}"
        # headers:
        #   Accept: "application/json"
        #   Content-Type: "application/json"

